on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
name: Check for broken links
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
